services:
  - type: web
    name: solosano-mvp
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    branch: master
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: "oracle+oracledb://rm98044:070305@oracle.fiap.com.br:1521/ORCL"
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"
      - key: ORACLE_HOST
        value: oracle.fiap.com.br
      - key: ORACLE_PORT
        value: 1521
      - key: ORACLE_SERVICE
        value: ORCL
      - key: ORACLE_USER
        value: rm98044
      - key: ORACLE_PASSWORD
        value: "070305"
      - key: SECRET_KEY
        value: sua_chave_secreta_aqui
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30 